version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-eccomerse
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
  # postgres:
  #   image: postgres:16.2
  #   container_name: postgres-eccomerse
  #   restart: always
  #   environment:
  #     POSTGRES_DB: eccomerse
  #     POSTGRES_USER: syafiq
  #     POSTGRES_PASSWORD: 'root'
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: