name: build

on:
    push:
        branches:
            - develop
    

jobs:
    lint:
        name: Check linter

        runs-on: ubuntu/22.04
        steps:
            - name: Check repository
              uses: actions/checkout@v4
            
            - name: Install eslint
                
            - name: Install bun
              uses: oven-sh/setup-bun@v1
              with:
                bun-version: latest

            - name: Install dependencies on backend
              run: cd backend && bun install --frozen-lockfile

            


